# Generated by Django 3.0.5 on 2020-07-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caract_bedroom', models.CharField(choices=[('Standard', 'Standard'), ('Master', 'Master'), ('Delux', 'Delux'), ('Outros', 'Outros')], max_length=10)),
                ('type_bedroom', models.CharField(choices=[('Quarto Solteiro', 'Quarto Solteiro'), ('Quarto Duplo', 'Quarto Duplo'), ('Quarto Casal', 'Quarto Casal'), ('Outros', 'Outros')], max_length=20)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('preco', models.FloatField()),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
            ],
        ),
    ]
