# Generated by Django 3.0.5 on 2020-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caract_bedroom', models.CharField(choices=[(1, 'Standard'), (2, 'Master'), (3, 'Delux'), (4, 'Outros')], max_length=10)),
                ('type_bedroom', models.CharField(choices=[('1', 'Quarto Solteiro'), ('2', 'Quarto Duplo'), ('3', 'Quarto Casal'), ('4', 'Outros')], max_length=20)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('preco', models.FloatField()),
                ('hotel', models.ManyToManyField(to='alojamento.Alojamento')),
            ],
        ),
    ]
