# Generated by Django 3.0.5 on 2020-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='Caract_bedroom',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Master', 'Master'), ('Delux', 'Delux'), ('Outros', 'Outros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='type_bedroom',
            field=models.CharField(choices=[('Quarto Solteiro', 'Quarto Solteiro'), ('Quarto Duplo', 'Quarto Duplo'), ('Quarto Casal', 'Quarto Casal'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
