# Generated by Django 3.0.5 on 2020-06-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200623_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
