# Generated by Django 3.0.5 on 2020-06-26 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_auto_20200626_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='UserLembrete',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
