# Generated by Django 3.0.5 on 2020-06-26 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamento', '0005_remove_alojamento_comentarios'),
        ('eventos', '0006_eventolembret'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hotel_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
