# Generated by Django 3.0.5 on 2020-06-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
