# Generated by Django 3.0.5 on 2020-07-18 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ImagensPerfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Type_Alojamento', models.CharField(choices=[('Hotel', 'Hotel'), ('Apart-hotel', 'Apart-hotel'), ('Residencial/Pensão', 'Residencial/Pensão'), ('Resort/Lodge', 'Resort/Lodge'), ('Outros', 'Outros')], max_length=20)),
                ('Estrela', models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, ' 5 estrelas')])),
                ('Aprovado', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('pais', models.CharField(max_length=50)),
                ('Provincia', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('linha', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('imgs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagensPerfil.Imagens')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
