# Generated by Django 3.0.5 on 2020-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='Estrela',
            field=models.CharField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, ' 5 estrelas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alojamento',
            name='Type_Alojamento',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Apart-hotel', 'Apart-hotel'), ('Residencial/Pensão', 'Residencial/Pensão'), ('Resort/Lodge', 'Resort/Lodge'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
