# Generated by Django 3.0.5 on 2020-06-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0002_auto_20200620_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='Estrela',
            field=models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, ' 5 estrelas')]),
        ),
    ]
