# Generated by Django 3.0.5 on 2020-12-04 13:12

import alojamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0003_alojamento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=alojamento.models.uploud_image),
        ),
    ]
