# Generated by Django 3.0.5 on 2020-06-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0004_alojamento_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamento',
            name='comentarios',
        ),
    ]
