# Generated by Django 3.0.5 on 2020-06-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0005_remove_alojamento_comentarios'),
        ('comentarios', '0002_comentario_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='hotel',
        ),
        migrations.AddField(
            model_name='comentario',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento'),
            preserve_default=False,
        ),
    ]
