# Generated by Django 3.0.5 on 2020-06-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_auto_20200626_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='owner',
        ),
    ]
