# Generated by Django 3.0.5 on 2020-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.BooleanField(default=True)),
                ('Quarto_Solteiro', models.BooleanField(default=False)),
                ('Quarto_Duplo', models.BooleanField(default=False)),
                ('Quarto_Casal', models.BooleanField(default=False)),
                ('Outros', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
