# Generated by Django 3.0.5 on 2020-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagensPerfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='hotel_owner',
            field=models.BooleanField(default=True),
        ),
    ]
