# Generated by Django 3.0.5 on 2020-07-18 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0002_remove_alojamento_imgs'),
        ('ImagensPerfil', '0002_imagens_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='hotel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento'),
        ),
    ]
