# Generated by Django 3.0.5 on 2020-11-30 14:26

import ImagensPerfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagensPerfil', '0003_auto_20200718_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='img',
            field=models.ImageField(upload_to=ImagensPerfil.models.uploud_image),
        ),
    ]
