# Generated by Django 3.0.5 on 2020-12-14 13:09

import ImagensPerfil.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0004_auto_20201204_1412'),
        ('quartos', '0001_initial'),
        ('ImagensPerfil', '0004_auto_20201130_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=ImagensPerfil.models.uploud_image)),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
                ('quarto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.Quarto')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
