# Generated by Django 3.0.5 on 2020-12-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagensPerfil', '0005_auto_20201214_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='quarto_id',
            new_name='quarto',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='hotel_owner',
        ),
    ]
