# Generated by Django 3.0.5 on 2020-10-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguir',
            old_name='User',
            new_name='User_id',
        ),
        migrations.RenameField(
            model_name='seguir',
            old_name='hotel',
            new_name='hotel_id',
        ),
    ]
