# Generated by Django 3.0.5 on 2020-06-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0001_initial'),
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_preco', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('valid_data', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.Alojamento')),
                ('quartos_em_prom', models.ManyToManyField(to='quartos.Quarto')),
            ],
        ),
    ]
